apiVersion: v2
name: workload-identity-webhook
description: A Helm chart to install the azure-workload-identity webhook
type: application
version: 1.0.0-beta.0
appVersion: v1.0.0-beta.0
home: https://github.com/Azure/azure-workload-identity
sources:
  - https://github.com/Azure/azure-workload-identity
