apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  labels:
    app: '{{ template "workload-identity-webhook.name" . }}'
    azure-workload-identity.io/system: "true"
    chart: '{{ template "workload-identity-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-wi-webhook-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: azure-wi-webhook-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-pod
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: mutation.azure-workload-identity.io
  {{- if .Values.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.namespaceSelector | nindent 4 }}
  {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
