apiVersion: v1
entries:
  workload-identity-webhook:
  - apiVersion: v2
    appVersion: v1.0.0-beta.0
    created: "2023-03-01T20:47:01.015022926Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: d062d175969a537dbe0ccb2821a3c16c2bc625bbcaf368157e7fca252c495f81
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-1.0.0-beta.0.tgz
    version: 1.0.0-beta.0
  - apiVersion: v2
    appVersion: v1.0.0-alpha.0
    created: "2023-02-08T18:18:27.98374562Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: aa5a98619ac0f1643bd33e007cc69cfc7bdc9d02da78f80ff21eeb6e80f38ab0
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-1.0.0-alpha.0.tgz
    version: 1.0.0-alpha.0
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2022-12-13T23:13:29.040336352Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 33c21e32d50dd802e872a52d62e1f11923674e2759f0bce5d15f040f3b70f023
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.15.0.tgz
    version: 0.15.0
  - apiVersion: v2
    appVersion: v0.14.0
    created: "2022-11-28T20:55:28.970097881Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: e92648ad47491911b04b03e49a2457aeb592580af045e1a4303660a58a7b7d6c
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.14.0.tgz
    version: 0.14.0
  - apiVersion: v2
    appVersion: v0.13.0
    created: "2022-10-12T16:42:45.64941286Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 510b9b915de8663e1bb9c7fa03f7ff0b981386ec54d115e1b60e4ab4d98cfab1
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.13.0.tgz
    version: 0.13.0
  - apiVersion: v2
    appVersion: v0.12.0
    created: "2022-07-26T18:53:17.738458584Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 800bc71b1a089f560db751a6c218188552c2c1fc6addead96be8338144d9db0d
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.12.0.tgz
    version: 0.12.0
  - apiVersion: v2
    appVersion: v0.11.0
    created: "2022-06-29T19:21:11.614825195Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 3d6a759b5455c8d8e2fcf0111c8731ea27729637326e51173d63ba8fa7042592
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: v0.10.0
    created: "2022-05-11T17:55:12.798382793Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: cdcf6b127c4bfc2ec33657e3623046fa12ff3423a15cb07fb84cdf670c17ba15
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2022-03-28T19:58:43.99777953Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: c2a89ea530140e553610a607c5ac41d54c1cd0ac7a33d3b98394e35242b83f80
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: v0.8.0
    created: "2022-03-09T18:45:12.477670618Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 69b0c83d0b68500c5aa644401a045a0d1c5714ade14e85187f53f649763b2043
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: v0.7.0
    created: "2022-02-07T19:13:35.068865025Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 8b45401f724fff91c11fc77fcb79964a574626c4905ee292a80fffa6f099c051
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: v0.6.0
    created: "2022-02-07T19:13:35.068349792Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: c5ee3d5e3d65a5bb293ae791db7c4dbae0fb2172c368a482e12a432c6781e350
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: v0.5.0
    created: "2022-02-07T19:13:35.067770141Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 0d551fb94dac546dd21733590a7856975ec970d370f1d09c4e7f4fae63b924ab
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: v0.4.0
    created: "2022-02-07T19:13:35.067228401Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 85dfa90279627ce09c3b8c6a302d35620e5dbf5fd617c9b44e1fd5c1deda4567
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.4.0.tgz
    version: 0.4.0
generated: "2023-03-01T20:47:01.013954429Z"
