apiVersion: v1
entries:
  workload-identity-webhook:
  - apiVersion: v2
    appVersion: v0.12.0
    created: "2022-07-26T18:53:17.738458584Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 800bc71b1a089f560db751a6c218188552c2c1fc6addead96be8338144d9db0d
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.12.0.tgz
    version: 0.12.0
  - apiVersion: v2
    appVersion: v0.11.0
    created: "2022-06-29T19:21:11.614825195Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 3d6a759b5455c8d8e2fcf0111c8731ea27729637326e51173d63ba8fa7042592
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: v0.10.0
    created: "2022-05-11T17:55:12.798382793Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: cdcf6b127c4bfc2ec33657e3623046fa12ff3423a15cb07fb84cdf670c17ba15
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2022-03-28T19:58:43.99777953Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: c2a89ea530140e553610a607c5ac41d54c1cd0ac7a33d3b98394e35242b83f80
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: v0.8.0
    created: "2022-03-09T18:45:12.477670618Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 69b0c83d0b68500c5aa644401a045a0d1c5714ade14e85187f53f649763b2043
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: v0.7.0
    created: "2022-02-07T19:13:35.068865025Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 8b45401f724fff91c11fc77fcb79964a574626c4905ee292a80fffa6f099c051
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: v0.6.0
    created: "2022-02-07T19:13:35.068349792Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: c5ee3d5e3d65a5bb293ae791db7c4dbae0fb2172c368a482e12a432c6781e350
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: v0.5.0
    created: "2022-02-07T19:13:35.067770141Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 0d551fb94dac546dd21733590a7856975ec970d370f1d09c4e7f4fae63b924ab
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: v0.4.0
    created: "2022-02-07T19:13:35.067228401Z"
    description: A Helm chart to install the azure-workload-identity webhook
    digest: 85dfa90279627ce09c3b8c6a302d35620e5dbf5fd617c9b44e1fd5c1deda4567
    home: https://github.com/Azure/azure-workload-identity
    name: workload-identity-webhook
    sources:
    - https://github.com/Azure/azure-workload-identity
    type: application
    urls:
    - https://Azure.github.io/azure-workload-identity/charts/workload-identity-webhook-0.4.0.tgz
    version: 0.4.0
generated: "2022-07-26T18:53:17.737435096Z"
